version: '3.1'

services:

  postgres:
    build: ./database
    restart: always
    command: postgres -c shared_buffers=16384 -c shared_preload_libraries='pg_stat_statements' -c track_activity_query_size=2048 -c pg_stat_statements.track=all
    container_name: latoken-postgres
    env_file:
      - ./tg_bot/.env
    environment:
      POSTGRES_USER: latoken
      POSTGRES_DB: latoken_bot
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bot-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  tg_bot:
    build: ./tg_bot
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./tg_bot/.env
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
    external: true