FROM python:3.11-slim

# Сначала копируем зависимости для кэширования
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Затем копируем остальные файлы
COPY . .

ENV DOCKER_ENV=true

CMD ["python", "bot_main.py"]